<?php
/**
 * Copyright © 2011-2017 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * 
 * See COPYING.txt for license details.
 */
?>
<?php if ($block->isEnabled()) : ?>
	<?php $count = $block->getCounter() ?>
	<?php if (0 < $count) : ?>
		<div class="wishlist-score"><?php /* @escapeVerified */ echo $block->escapeHtml(__('%1 people added this product to Wish List', $count)) ?></div>
	<?php endif ?>
<?php endif ?>
